name: 'GitHub Copilot CLI'
description: 'GitHub Copilot CLI wrapper'
branding:
  icon: 'cpu'
  color: 'purple'
inputs:
  copilot-token:
    description: 'GitHub Personal Access Token (PAT) with "Copilot Requests" permission. The default github.token does NOT have Copilot access - you must provide a PAT with the "Copilot Requests" scope. See: https://github.com/settings/tokens/new?scopes=copilot'
    required: true
  repo-token:
    description: 'Token for standard GitHub repository operations (e.g., pushing commits, creating PRs). Defaults to copilot-token if not specified. You can use the default GITHUB_TOKEN here if you only need repo access.'
    required: false
    default: ${{ github.token }}
  prompt:
    description: 'Prompt to send to GitHub Copilot'
    required: true
  mcp-config:
    description: 'MCP configuration for GitHub Copilot [Link](https://docs.github.com/en/copilot/how-tos/use-copilot-agents/coding-agent/extend-coding-agent-with-mcp#writing-a-json-configuration-for-mcp-servers)'
    required: false
  copilot-config:
    description: 'Configuration for GitHub Copilot'
    required: false
    default: |
      {
        "banner": "never",
        "render_markdown": true,
        "theme": "auto",
        "trusted_folders": []
      }
  allow-all-tools:
    description: 'Allow all tools without approval'
    required: false
    default: 'true'
  allowed-tools:
    description: 'Comma-separated list of tools to allow (e.g., "shell(rm),shell(git push)")'
    required: false
  denied-tools:
    description: 'Comma-separated list of tools to deny (e.g., "shell(rm),shell(git push)")'
    required: false
  copilot-version:
    description: 'Version of @github/copilot to install (e.g., "latest", "0.0.329")'
    required: false
    default: 'latest'
  model:
    description: 'Model to use (e.g., "claude-sonnet-4.5", "claude-sonnet-4", "gpt-5")'
    required: false
  additional-directories:
    description: 'Comma-separated list of additional directories to trust for file access (e.g., "/tmp,/var/log")'
    required: false
  disable-mcp-servers:
    description: 'Comma-separated list of MCP servers to disable (e.g., "github-mcp-server,custom-server")'
    required: false
  enable-all-github-mcp-tools:
    description: 'Enable all GitHub MCP tools'
    required: false
    default: 'false'
  resume-session:
    description: 'Resume from a previous session ID (use "latest" for most recent)'
    required: false
  upload-artifact:
    description: 'Upload artifact after running Copilot'
    required: false
    default: true
  agent:
    description: 'Specify a custom agent to use'
    required: false
  log-level:
    description: 'Set the log level (choices: "none", "error", "warning", "info", "debug", "all", "default")'
    required: false
    default: 'all'
outputs:
  logs-path:
    description: 'Path to the copilot logs directory'
    value: ${{ steps.copilot.outputs.logs_path }}
  exit-code:
    description: 'Exit code from the Copilot CLI command'
    value: ${{ steps.copilot.outputs.exit_code }}
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v6
      with:
        node-version: '22'
    - name: Run GitHub Copilot CLI
      id: copilot
      shell: bash
      run: |
        echo "::group::Verify GitHub Auth"
        gh auth status
        echo "::endgroup::"
        
        echo "::group::Install GitHub Copilot CLI"
        if [ "$COPILOT_VERSION" = "latest" ]; then
          npm install -g @github/copilot
        else
          npm install -g @github/copilot@$COPILOT_VERSION
        fi
        echo "::endgroup::"

        copilot --version || echo "Warning: Could not get copilot version"
        
        echo "::group::Configure Copilot MCP"
        if [ -n "$MCP_CONFIG" ]; then
          cat $XDG_CONFIG_HOME/.copilot/mcp-config.json || echo "No existing MCP config found"
          mkdir -p $XDG_CONFIG_HOME/.copilot
          
          BASE_MCP_CONFIG='{
            "mcpServers": { }
          }'

          MERGED_MCP_CONFIG=$(echo "$BASE_MCP_CONFIG" | jq --argjson user "$MCP_CONFIG" '.mcpServers += $user.mcpServers')
          echo "$MERGED_MCP_CONFIG" > $XDG_CONFIG_HOME/.copilot/mcp-config.json
          cat $XDG_CONFIG_HOME/.copilot/mcp-config.json
        fi
        echo "::endgroup::"
        
        echo "::group::Build Copilot Args"
        COPILOT_ARGS=""

        COPILOT_ARGS+="--add-dir / "
        if [ -n "$ADDITIONAL_DIRS" ]; then
          IFS=',' read -ra DIRS <<< "$ADDITIONAL_DIRS"
          for dir in "${DIRS[@]}"; do
            COPILOT_ARGS+="--add-dir $dir "
          done
        fi
        if [ -n "$DISABLE_MCP_SERVERS" ]; then
          IFS=',' read -ra SERVERS <<< "$DISABLE_MCP_SERVERS"
          for server in "${SERVERS[@]}"; do
            COPILOT_ARGS+="--disable-mcp-server $server "
          done
        fi
        if [ "$ENABLE_ALL_GITHUB_MCP_TOOLS" = "true" ]; then
          COPILOT_ARGS+="--enable-all-github-mcp-tools "
        fi
        if [ "$ALLOW_ALL_TOOLS" = "true" ]; then
          COPILOT_ARGS+="--allow-all-tools "
        fi
        if [ -n "$ALLOWED_TOOLS" ]; then
          IFS=',' read -ra TOOLS <<< "$ALLOWED_TOOLS"
          for tool in "${TOOLS[@]}"; do
            COPILOT_ARGS+="--allow-tool $tool "
          done
        fi
        if [ -n "$DENIED_TOOLS" ]; then
          IFS=',' read -ra TOOLS <<< "$DENIED_TOOLS"
          for tool in "${TOOLS[@]}"; do
            COPILOT_ARGS+="--deny-tool $tool "
          done
        fi
        if [ -n "$MODEL" ]; then
          COPILOT_ARGS+="--model $MODEL "
        fi
        if [ -n "$AGENT" ]; then
          COPILOT_ARGS+="--agent $AGENT "
        fi
        if [ -n "$RESUME_SESSION" ]; then
          if [ "$RESUME_SESSION" = "latest" ]; then
            COPILOT_ARGS+="--continue "
          else
            COPILOT_ARGS+="--resume $RESUME_SESSION "
          fi
        fi
        if [ -n "$LOG_LEVEL" ]; then
          COPILOT_ARGS+="--log-level $LOG_LEVEL "
        fi
        COPILOT_ARGS+="--log-dir $HOME/.copilot/logs"

        echo "$COPILOT_ARGS"
        echo "::endgroup::"

        echo "::group::Run Copilot CLI"
        set +e
        copilot -p "$PROMPT" $COPILOT_ARGS
        EXIT_CODE=$?
        echo "::endgroup::"

        echo "logs_path=$HOME/.copilot/logs" >> $GITHUB_OUTPUT
        echo "exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ inputs.repo-token || inputs.copilot-token }}
        COPILOT_GITHUB_TOKEN: ${{ inputs.copilot-token }}
        PROMPT: ${{ inputs.prompt }}
        COPILOT_VERSION: ${{ inputs.copilot-version }}
        CONFIG: ${{ inputs.copilot-config }}
        MCP_CONFIG: ${{ inputs.mcp-config }}
        ALLOW_ALL_TOOLS: ${{ inputs.allow-all-tools }}
        ALLOWED_TOOLS: ${{ inputs.allowed-tools }}
        DENIED_TOOLS: ${{ inputs.denied-tools }}
        MODEL: ${{ inputs.model }}
        AGENT: ${{ inputs.agent }}
        ADDITIONAL_DIRS: ${{ inputs.additional-directories }}
        DISABLE_MCP_SERVERS: ${{ inputs.disable-mcp-servers }}
        ENABLE_ALL_GITHUB_MCP_TOOLS: ${{ inputs.enable-all-github-mcp-tools }}
        RESUME_SESSION: ${{ inputs.resume-session }}
        LOG_LEVEL: ${{ inputs.log-level }}
    - name: Upload Copilot Artifacts
      uses: actions/upload-artifact@v4
      if: ${{ always() && inputs.upload-artifact == 'true' }}
      with:
        name: copilot-logs-${{ github.run_id }}-${{ github.run_attempt }}
        path: |
          ~/.copilot/logs
        if-no-files-found: warn
