name: 'Dependabot Update with Copilot'
description: 'Updates code for Dependabot dependency updates using GitHub Copilot'
inputs:
  github-token:
    description: 'GitHub Personal Access Token with required permissions'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Dependabot metadata
      id: metadata
      uses: dependabot/fetch-metadata@d7267f607e9d3fb96fc2fbe83e0af444713e90b7
      with:
        github-token: "${{ github.token }}"
    - uses: austenstone/copilot-cli-actions/.github/actions/copilot@main
      with:
        github-token: ${{ inputs.github-token }}
        prompt: |
          Dependabot has opened a pull request to update dependencies.
          Research and understand code changes required to update the dependencies.
          Update the code as necessary to ensure compatibility with the new versions.
          Create a pull request with the necessary changes.

          GitHub Context: ${{ toJson(github) }}
          Dependabot Metadata: ${{ toJson(steps.metadata.outputs) }}