name: 'CI Fix with Copilot'
description: 'Analyzes failed CI workflow runs and creates PRs with fixes using GitHub Copilot'
inputs:
  github-token:
    description: 'GitHub Personal Access Token with required permissions'
    required: true
outputs:
  outcome:
    description: 'Summary of the action outcome'
    value: ${{ steps.copilot.outputs.outcome }}
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v5
    - run: npm install -g @github/copilot
      shell: bash
    - run: |
        mkdir -p ~/.copilot
        cat > ~/.copilot/mcp-config.json << 'EOF'
        {
          "mcpServers": {
            "actions-toolkit-mcp": {
              "type": "local",
              "command": "npx",
              "tools": [ "*" ],
              "args": ["-y", "actions-toolkit-mcp"]
            }
          }
        }
        EOF
      shell: bash
    - run: copilot -p "$PROMPT" --allow-all-tools
      id: copilot
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        PROMPT: |
          First list all your tools.

          The GitHub Actions workflow run failed.
          Please analyze the failure and suggest a fix.
          Create a pull request with the necessary changes.
          Include the error logs and any relevant information.

          At the end, summarize the outcome of your task using "actions-toolkit-mcp" mcp tool

          Workflow Run: ${{ github.event.workflow_run.url }}
          GitHub Context: ${{ toJson(github) }}
    - if: ${{ steps.copilot.outputs.outcome }}
      run: echo "::notice::${{ steps.copilot.outputs.outcome }}"
      shell: bash
