name: 'CI Fix with Copilot'
description: 'Analyzes failed CI workflow runs and creates PRs with fixes using GitHub Copilot'
inputs:
  github-token:
    description: 'GitHub Personal Access Token with required permissions'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: austenstone/copilot-cli-actions/.github/actions/copilot@main
      with:
        github-token: ${{ inputs.github-token }}
        prompt: |
          The GitHub Actions workflow run failed.
          Please analyze the failure and suggest a fix.
          Create a pull request with the necessary changes.
          Include the error logs and any relevant information.

          At the end, summarize the outcome of your task using "actions-toolkit-mcp" mcp tool

          Workflow Run: ${{ github.event.workflow_run.url }}
          GitHub Context: ${{ toJson(github) }}