name: 'Copilot Command'
description: 'Executes Copilot CLI commands from issue comments'
inputs:
  github-token:
    description: 'GitHub Personal Access Token with required permissions'
    required: true
  prompt:
    description: 'The prompt/command to execute'
    required: true
outputs:
  outcome:
    description: 'Summary of the action outcome'
    value: ${{ steps.copilot.outputs.outcome }}
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v5
    - run: npm install -g @github/copilot
      shell: bash
    - run: copilot -p "$PROMPT" --allow-all-tools
      id: copilot
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        PROMPT: |
          ${{ inputs.prompt }}

          Context: ${{ toJson(github) }}

          At the end, summarize the outcome of your task like this
          Format: echo "outcome={value}" >> "$GITHUB_OUTPUT"
    - if: ${{ steps.copilot.outputs.outcome }}
      run: echo "::notice::${{ steps.copilot.outputs.outcome }}"
      shell: bash
