name: 'GitHub Copilot CLI'
description: 'GitHub Copilot CLI wrapper'
inputs:
  github-token:
    description: 'GitHub Personal Access Token with required permissions'
    required: true
  prompt:
    description: 'Prompt to send to GitHub Copilot'
    required: true
  mcp-config:
    description: 'MCP configuration for GitHub Copilot'
    required: false
    default: |
      {
        "mcpServers": { }
      }
  copilot-config:
    description: 'Configuration for GitHub Copilot'
    required: false
    default: |
      {
        "banner": "never",
        "render_markdown": true,
        "screen_reader": false,
        "theme": "auto",
        "trusted_folders": [
          "/home/runner"
        ]
      }
  log-level:
    description: 'Log level for GitHub Copilot'
    required: false
    default: 'all'
  upload-artifact:
    description: 'Upload artifact after running Copilot'
    required: false
    default: true
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
    - run: npm install -g @github/copilot
      shell: bash
    - run: |
        mkdir -p $XDG_CONFIG_HOME/.copilot

        echo '$MCP_CONFIG' > $XDG_CONFIG_HOME/.copilot/mcp-config.json
        cat $XDG_CONFIG_HOME/.copilot/mcp-config.json

        echo "$CONFIG" > $XDG_CONFIG_HOME/.copilot/config.json
        cat $XDG_CONFIG_HOME/.copilot/config.json
      shell: bash
      env:
        CONFIG: ${{ inputs.copilot-config }}
        MCP_CONFIG: ${{ inputs.mcp-config }}
    - run: copilot -p "$PROMPT" --allow-all-tools --log-level "$LOG_LEVEL" --log-dir ~/.copilot/logs --save-trajectory-output ~/.copilot/trajectory.md
      id: copilot
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        PROMPT: ${{ inputs.prompt }}
        LOG_LEVEL: ${{ inputs.log-level }}
      shell: bash
    - uses: actions/upload-artifact@v4
      if: ${{ inputs.upload-artifact }}
      with:
        name: copilot-logs
        path: |
          ~/.copilot/logs/
          ~/.copilot/trajectory.md
          /home/runner/.config/
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3