name: 'GitHub Copilot CLI'
description: 'GitHub Copilot CLI wrapper'
inputs:
  github-token:
    description: 'GitHub Personal Access Token with required permissions'
    required: true
  prompt:
    description: 'Prompt to send to GitHub Copilot'
    required: true
  upload-artifact:
    description: 'Upload artifact after running Copilot'
    required: false
    default: true
  mcp-config:
    description: 'MCP configuration for GitHub Copilot'
    required: false
    default: |
      {
        "mcpServers": { }
      }
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
    - run: npm install -g @github/copilot
      shell: bash
    - run: |
        mkdir -p $XDG_CONFIG_HOME/.copilot
        
        ACTIONS_TOOLKIT_MCP='{
          "actions-toolkit-mcp": {
            "command": "npx",
            "args": ["-y", "actions-toolkit-mcp"],
            "tools": ["*"],
            "env": {
              "GITHUB_STEP_SUMMARY": "${GITHUB_STEP_SUMMARY}",
              "GITHUB_ENV": "${GITHUB_ENV}",
              "RUNNER_DEBUG": "${RUNNER_DEBUG}",
              "GITHUB_SERVER_URL": "${GITHUB_SERVER_URL}",
              "GITHUB_REPOSITORY": "${GITHUB_REPOSITORY}",
              "GITHUB_EVENT_PATH": "${GITHUB_EVENT_PATH}"
            }
          }
        }'
        
        # Merge user-provided MCP config with hardcoded config
        echo '${{ inputs.mcp-config }}' | jq --argjson toolkit "$ACTIONS_TOOLKIT_MCP" \
          '.mcpServers += $toolkit' > $XDG_CONFIG_HOME/.copilot/mcp-config.json
        cat $XDG_CONFIG_HOME/.copilot/mcp-config.json
      env:
        GITHUB_STEP_SUMMARY: ${{ github.step_summary }}
        GITHUB_ENV: ${{ github.env }}
        RUNNER_DEBUG: ${{ runner.debug }}
        GITHUB_SERVER_URL: ${{ github.server_url }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_EVENT_PATH: ${{ github.event_path }}
      shell: bash
    - run: |
        ls -al $XDG_CONFIG_HOME/.copilot
        CONFIG='{
          "banner": "never",
          "render_markdown": true,
          "screen_reader": false,
          "theme": "auto",
          "trusted_folders": [
            "/home/runner"
          ]
        }'
        echo "$CONFIG" > $XDG_CONFIG_HOME/.copilot/config.json
        cat $XDG_CONFIG_HOME/.copilot/config.json
      shell: bash
    - run: copilot -p "$PROMPT" --allow-all-tools --log-level all --log-dir ~/.copilot/logs --save-trajectory-output ~/.copilot/trajectory.md
      id: copilot
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        PROMPT: ${{ inputs.prompt }}
      shell: bash
    - uses: actions/upload-artifact@v4
      if: ${{ inputs.upload-artifact }}
      with:
        name: copilot-logs
        path: |
          ~/.copilot/logs/
          ~/.copilot/trajectory.md
          /home/runner/.config/

    