on:
  workflow_run:
    workflows: [CI] # add workflows here
    types: [completed]

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - uses: actions/checkout@v5
      - run: npm install -g @github/copilot
      - run: |
          copilot -p "The job failed in the GitHub Actions workflow run. Please analyze the failure and suggest a fix. Create a pull request with the necessary changes. workflow_run: $WORKFLOW_RUN" --allow-all-tools
        env:
          GH_TOKEN: ${{ secrets.PAT }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
          WORKFLOW_RUN: ${{ github.event.workflow_run.url }}