on:
  workflow_run:
    workflows: [CI] # add workflows here
    types: [completed]

jobs:
  on-failure:
    runs-on: ubuntu-latest
    concurrency:
      group: ci-fix
      cancel-in-progress: true
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - uses: actions/checkout@v5
      - run: npm install -g @github/copilot
      - run: |
          echo $PROMPT
          copilot -p "$PROMPT" --allow-all-tools
        env:
          GH_TOKEN: ${{ secrets.PAT }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
          WORKFLOW_RUN: ${{ github.event.workflow_run.url }}
          PROMPT: |
            The job failed in the GitHub Actions workflow run.
            Please analyze the failure and suggest a fix.
            Create a pull request with the necessary changes.
            Include the error logs and any relevant information.
            
            Workflow Run: $WORKFLOW_RUN
            GitHub Context: $GITHUB_CONTEXT