on: issue_comment

jobs:
  copilot:
    if: ${{ startsWith(github.event.comment.body, '/copilot') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: npm install -g @github/copilot
      - run: copilot -p "$PROMPT" --allow-all-tools
        id: copilot
        env:
          GH_TOKEN: ${{ secrets.PAT }}
          PROMPT: |
            ${{ github.event.comment.body }}

            Context: ${{ toJson(github) }}

            At the end, summarize the outcome of your task like this
            Format: echo "outcome={value}" >> "$GITHUB_OUTPUT"
      - if: ${{ steps.copilot.outputs.outcome }}
        run: echo "::notice::${{ steps.copilot.outputs.outcome }}"
